spring:
  application:
    name: geuphalttaen

  config:
    import:
      - classpath:config/db.yml
      - classpath:config/redis.yml
      - classpath:config/jwt.yml
      - classpath:config/opendata.yml

  task:
    scheduling:
      pool:
        size: 2

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info
