spring:
  application:
    name: geuphalttaen

  profiles:
    include:
      - db
      - redis
      - jwt
      - opendata
      - ncp
      - kakao

  task:
    scheduling:
      pool:
        size: 2

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info
