app = "geuphalttaen-mysql"
primary_region = "nrt"

[build]
  image = "mysql:8.0"

[deploy]
  strategy = "immediate"

[env]
  MYSQL_DATABASE = "geuphalttaen"

[[mounts]]
  source = "geuphalttaen_mysql_data"
  destination = "/var/lib/mysql"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
